require("sascha.plugins-setup")

require("sascha.core.colorscheme")
require("sascha.core.keymaps")
require("sascha.core.options")

require("sascha.plugins.lsp.lspsaga")
require("sascha.plugins.lsp.lspconfig")
require("sascha.plugins.lsp.mason")
require("sascha.plugins.lsp.null-ls")
require("sascha.plugins.autopairs")
require("sascha.plugins.comment")
require("sascha.plugins.gitsigns")
require("sascha.plugins.lualine")
require("sascha.plugins.nvim-cmp")
require("sascha.plugins.nvim-tree")
require("sascha.plugins.telescope")
require("sascha.plugins.treesitter")
