import = [
  "~/.config/alacritty/catppuccin-mocha.toml"
]

live_config_reload = true

[env]
TERM = "xterm-256color"

[font]
size = 16.0

[font.normal]
family = "SFMono Nerd Font"
style = "Medium"

[window]
decorations = "buttonless"
dynamic_padding = false
opacity = 0.8

[window.padding]
x = 12
y = 8
